language: java
jdk:
- oraclejdk8
before_deploy: gradle capsule
deploy:
  provider: releases
  api_key:
    secure: b7e1mQdSuxvLG0KVY3GdxaQA3ihte1M8C//aHLBts0M/FBdAvKQ/GBfwKv+jC0/OWcu9fR2ux6xcA1i4kPxEpq/CobsBaJybESKNyv7bC8vHIwyxsXeZF8Fy/PwLDwLFmWgxzH5z9saZ2ivuJYiBbUncFUiMqyGCTBXJRlm2YmzcFoOMcZSmrvIg1AdWy+3JAKBmuon3TsaJPXhIVZvDonxUA+k3rXB5VqJQ/tNOnb6EteDkLbtT2ybvaX9mPiLdYyotXXXx1i3POBV+LXnZzOp+Ju+ldiFB0JsOFvGhtFEhfMPshIj1M9O8r/MyztQIoc5DE/bzoN4J3yGk1A8nc6QzEWRdI2WA8LHLWb9u79tDNmNO2ljKHK6fWLCy/NKw+Swow3zhveSYVYK1/BzQcKZWgw0t8oNRSRXbZft/iK6rSzYv7o15Hnzms5OARv6LNGOimTpsWh5gvViUDuCAO4Hv/x36hcojr27RLirHW88Bt0fEnKazz3Sw0gDUlhNfUYv+0JVJKGLetsgVyta79A7SSWKjM8IDTv230XGbWTEpaiAK8mLgcqiBkQF8qfZDehydgmSthbW3zS/06DZ6Tn3pVCXeEC/WzyeS3rgzAnKnZXCMyFgSkitdeguF6wbyulgGxVEN3TZD0jMLXEXv5Idh2wXdg0Acj8nYRYw4FYY=
  file: "./build/libs/marissa-capsule.jar"
  skip_cleanup: true
  on:
    repo: marissabot/marissa
    tags: true
